-------------------------------------------------------------------------------
Test set: com.diana.integration.ControllerAndServiceAndDAOIntegration
-------------------------------------------------------------------------------
Tests run: 7, Failures: 0, Errors: 7, Skipped: 0, Time elapsed: 0.244 s <<< FAILURE! - in com.diana.integration.ControllerAndServiceAndDAOIntegration
testGetEmployees(com.diana.integration.ControllerAndServiceAndDAOIntegration)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in com.diana.config.PersistenceConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.jdbc.datasource.lookup.DataSourceLookupFailureException: Failed to look up JNDI DataSource with name 'jdbc/DB'; nested exception is javax.naming.NameNotFoundException: jdbc is not bound; remaining name 'jdbc/DB'
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.jdbc.datasource.lookup.DataSourceLookupFailureException: Failed to look up JNDI DataSource with name 'jdbc/DB'; nested exception is javax.naming.NameNotFoundException: jdbc is not bound; remaining name 'jdbc/DB'
Caused by: org.springframework.jdbc.datasource.lookup.DataSourceLookupFailureException: Failed to look up JNDI DataSource with name 'jdbc/DB'; nested exception is javax.naming.NameNotFoundException: jdbc is not bound; remaining name 'jdbc/DB'
Caused by: javax.naming.NameNotFoundException: jdbc is not bound

testGetInfo(com.diana.integration.ControllerAndServiceAndDAOIntegration)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in com.diana.config.PersistenceConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.jdbc.datasource.lookup.DataSourceLookupFailureException: Failed to look up JNDI DataSource with name 'jdbc/DB'; nested exception is javax.naming.NameNotFoundException: jdbc is not bound; remaining name 'jdbc/DB'
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.jdbc.datasource.lookup.DataSourceLookupFailureException: Failed to look up JNDI DataSource with name 'jdbc/DB'; nested exception is javax.naming.NameNotFoundException: jdbc is not bound; remaining name 'jdbc/DB'
Caused by: org.springframework.jdbc.datasource.lookup.DataSourceLookupFailureException: Failed to look up JNDI DataSource with name 'jdbc/DB'; nested exception is javax.naming.NameNotFoundException: jdbc is not bound; remaining name 'jdbc/DB'
Caused by: javax.naming.NameNotFoundException: jdbc is not bound

testAddExistingEmployee(com.diana.integration.ControllerAndServiceAndDAOIntegration)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in com.diana.config.PersistenceConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.jdbc.datasource.lookup.DataSourceLookupFailureException: Failed to look up JNDI DataSource with name 'jdbc/DB'; nested exception is javax.naming.NameNotFoundException: jdbc is not bound; remaining name 'jdbc/DB'
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.jdbc.datasource.lookup.DataSourceLookupFailureException: Failed to look up JNDI DataSource with name 'jdbc/DB'; nested exception is javax.naming.NameNotFoundException: jdbc is not bound; remaining name 'jdbc/DB'
Caused by: org.springframework.jdbc.datasource.lookup.DataSourceLookupFailureException: Failed to look up JNDI DataSource with name 'jdbc/DB'; nested exception is javax.naming.NameNotFoundException: jdbc is not bound; remaining name 'jdbc/DB'
Caused by: javax.naming.NameNotFoundException: jdbc is not bound

testRootRedirect(com.diana.integration.ControllerAndServiceAndDAOIntegration)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in com.diana.config.PersistenceConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.jdbc.datasource.lookup.DataSourceLookupFailureException: Failed to look up JNDI DataSource with name 'jdbc/DB'; nested exception is javax.naming.NameNotFoundException: jdbc is not bound; remaining name 'jdbc/DB'
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.jdbc.datasource.lookup.DataSourceLookupFailureException: Failed to look up JNDI DataSource with name 'jdbc/DB'; nested exception is javax.naming.NameNotFoundException: jdbc is not bound; remaining name 'jdbc/DB'
Caused by: org.springframework.jdbc.datasource.lookup.DataSourceLookupFailureException: Failed to look up JNDI DataSource with name 'jdbc/DB'; nested exception is javax.naming.NameNotFoundException: jdbc is not bound; remaining name 'jdbc/DB'
Caused by: javax.naming.NameNotFoundException: jdbc is not bound

testAddEmployee_MalformedName(com.diana.integration.ControllerAndServiceAndDAOIntegration)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in com.diana.config.PersistenceConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.jdbc.datasource.lookup.DataSourceLookupFailureException: Failed to look up JNDI DataSource with name 'jdbc/DB'; nested exception is javax.naming.NameNotFoundException: jdbc is not bound; remaining name 'jdbc/DB'
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.jdbc.datasource.lookup.DataSourceLookupFailureException: Failed to look up JNDI DataSource with name 'jdbc/DB'; nested exception is javax.naming.NameNotFoundException: jdbc is not bound; remaining name 'jdbc/DB'
Caused by: org.springframework.jdbc.datasource.lookup.DataSourceLookupFailureException: Failed to look up JNDI DataSource with name 'jdbc/DB'; nested exception is javax.naming.NameNotFoundException: jdbc is not bound; remaining name 'jdbc/DB'
Caused by: javax.naming.NameNotFoundException: jdbc is not bound

testGetInfo_notExisting(com.diana.integration.ControllerAndServiceAndDAOIntegration)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in com.diana.config.PersistenceConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.jdbc.datasource.lookup.DataSourceLookupFailureException: Failed to look up JNDI DataSource with name 'jdbc/DB'; nested exception is javax.naming.NameNotFoundException: jdbc is not bound; remaining name 'jdbc/DB'
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.jdbc.datasource.lookup.DataSourceLookupFailureException: Failed to look up JNDI DataSource with name 'jdbc/DB'; nested exception is javax.naming.NameNotFoundException: jdbc is not bound; remaining name 'jdbc/DB'
Caused by: org.springframework.jdbc.datasource.lookup.DataSourceLookupFailureException: Failed to look up JNDI DataSource with name 'jdbc/DB'; nested exception is javax.naming.NameNotFoundException: jdbc is not bound; remaining name 'jdbc/DB'
Caused by: javax.naming.NameNotFoundException: jdbc is not bound

testCreateEmp(com.diana.integration.ControllerAndServiceAndDAOIntegration)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in com.diana.config.PersistenceConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.jdbc.datasource.lookup.DataSourceLookupFailureException: Failed to look up JNDI DataSource with name 'jdbc/DB'; nested exception is javax.naming.NameNotFoundException: jdbc is not bound; remaining name 'jdbc/DB'
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.jdbc.datasource.lookup.DataSourceLookupFailureException: Failed to look up JNDI DataSource with name 'jdbc/DB'; nested exception is javax.naming.NameNotFoundException: jdbc is not bound; remaining name 'jdbc/DB'
Caused by: org.springframework.jdbc.datasource.lookup.DataSourceLookupFailureException: Failed to look up JNDI DataSource with name 'jdbc/DB'; nested exception is javax.naming.NameNotFoundException: jdbc is not bound; remaining name 'jdbc/DB'
Caused by: javax.naming.NameNotFoundException: jdbc is not bound

